-- Schema metadata only, no real user data.
create schema auth;create role authenticated;create role anon;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
grant usage on schema auth,public to authenticated,anon;
grant execute on function auth.uid() to authenticated,anon;
create table public.agenda_events (id uuid not null default gen_random_uuid(), user_id uuid not null , title text not null , notes text , life_area text not null default 'other'::text, event_kind text not null default 'obligation'::text, scheduled_start timestamp with time zone not null , scheduled_end timestamp with time zone , perceived_difficulty smallint , status text not null default 'planned'::text, completion_reason text , reviewed_at timestamp with time zone , source text not null default 'user'::text, created_at timestamp with time zone not null default now(), updated_at timestamp with time zone not null default now());
create table public.brain_versions (version text not null , status text not null , specification jsonb not null , created_at timestamp with time zone not null default now());
create table public.commitments (id uuid not null default gen_random_uuid(), user_id uuid not null , situation_id uuid , what text not null , why text , due_at timestamp with time zone , perceived_difficulty smallint , status text not null default 'pending'::text, created_at timestamp with time zone not null default now(), updated_at timestamp with time zone not null default now());
create table public.conversations (id uuid not null default gen_random_uuid(), user_id uuid not null , kind text not null default 'general'::text, title text , status text not null default 'open'::text, started_at timestamp with time zone not null default now(), ended_at timestamp with time zone );
create table public.goals (id uuid not null default gen_random_uuid(), user_id uuid not null , title text not null , why text , life_area text not null default 'self'::text, status text not null default 'active'::text, progress_state text not null default 'starting'::text, target_date date , last_progress_note text , last_progress_at timestamp with time zone , created_at timestamp with time zone not null default now(), updated_at timestamp with time zone not null default now());
create table public.hypotheses (id uuid not null default gen_random_uuid(), user_id uuid not null , statement text not null , evidence jsonb not null default '[]'::jsonb, confidence numeric(4,3) , status text not null default 'candidate'::text, user_feedback text , created_at timestamp with time zone not null default now(), updated_at timestamp with time zone not null default now());
create table public.memories (id uuid not null default gen_random_uuid(), user_id uuid not null , memory_type text not null , content text not null , structured_data jsonb not null default '{}'::jsonb, source_message_id uuid , life_area text , confidence numeric(4,3) , user_validation text not null default 'unreviewed'::text, sensitivity text not null default 'normal'::text, status text not null default 'candidate'::text, created_at timestamp with time zone not null default now(), updated_at timestamp with time zone not null default now());
create table public.messages (id uuid not null default gen_random_uuid(), user_id uuid not null , conversation_id uuid not null , role text not null , content text not null , created_at timestamp with time zone not null default now());
create table public.motivation_feedback (id uuid not null default gen_random_uuid(), user_id uuid not null , prompt_type text not null , content text not null , content_format text not null default 'text'::text, video_query text , rating smallint , created_at timestamp with time zone not null default now());
create table public.onboarding_sessions (id uuid not null default gen_random_uuid(), user_id uuid not null , conversation_id uuid , status text not null default 'in_progress'::text, current_dimension text , dimensions_covered jsonb not null default '[]'::jsonb, draft_profile jsonb not null default '{}'::jsonb, turn_count integer not null default 0, started_at timestamp with time zone not null default now(), completed_at timestamp with time zone );
create table public.people (id uuid not null default gen_random_uuid(), user_id uuid not null , name_or_label text not null , relationship text , notes text , user_validated boolean not null default false, created_at timestamp with time zone not null default now(), updated_at timestamp with time zone not null default now());
create table public.profile_items (id uuid not null default gen_random_uuid(), user_id uuid not null , category text not null , content text not null , epistemic_type text not null default 'user_declared'::text, source_message_id uuid , confidence numeric(4,3) not null default 1.0, user_validation text not null default 'unreviewed'::text, active boolean not null default true, created_at timestamp with time zone not null default now(), updated_at timestamp with time zone not null default now());
create table public.profiles (user_id uuid not null , onboarding_status text not null default 'not_started'::text, assistant_style jsonb not null default '{}'::jsonb, declared_self jsonb not null default '{}'::jsonb, desired_self jsonb not null default '{}'::jsonb, base_profile jsonb not null default '{}'::jsonb, profile_version integer not null default 1, validated_at timestamp with time zone , created_at timestamp with time zone not null default now(), updated_at timestamp with time zone not null default now());
create table public.situations (id uuid not null default gen_random_uuid(), user_id uuid not null , title text not null , life_area text , summary text , status text not null default 'open'::text, created_at timestamp with time zone not null default now(), updated_at timestamp with time zone not null default now());
alter table public.profile_items add constraint profile_items_category_check CHECK ((category = ANY (ARRAY['priority'::text, 'declared_value'::text, 'enjoyment'::text, 'distress'::text, 'tolerance'::text, 'boundary'::text, 'conflict_style'::text, 'decision_style'::text, 'change_style'::text, 'current_concern'::text, 'aspiration'::text, 'goal'::text, 'assistant_preference'::text, 'declared_trait'::text])));
alter table public.profile_items add constraint profile_items_epistemic_type_check CHECK ((epistemic_type = ANY (ARRAY['user_declared'::text, 'reported_event'::text, 'observed_repetition'::text, 'user_validated'::text])));
alter table public.profiles add constraint profiles_onboarding_status_check CHECK ((onboarding_status = ANY (ARRAY['not_started'::text, 'in_progress'::text, 'review'::text, 'completed'::text, 'skipped'::text])));
alter table public.profiles add constraint profiles_pkey PRIMARY KEY (user_id);
alter table public.people add constraint people_pkey PRIMARY KEY (id);
alter table public.conversations add constraint conversations_kind_check CHECK ((kind = ANY (ARRAY['onboarding'::text, 'general'::text, 'follow_up'::text])));
alter table public.conversations add constraint conversations_status_check CHECK ((status = ANY (ARRAY['open'::text, 'closed'::text])));
alter table public.conversations add constraint conversations_pkey PRIMARY KEY (id);
alter table public.messages add constraint messages_role_check CHECK ((role = ANY (ARRAY['user'::text, 'assistant'::text, 'system'::text])));
alter table public.messages add constraint messages_pkey PRIMARY KEY (id);
alter table public.memories add constraint memories_confidence_check CHECK (((confidence IS NULL) OR ((confidence >= (0)::numeric) AND (confidence <= (1)::numeric))));
alter table public.memories add constraint memories_user_validation_check CHECK ((user_validation = ANY (ARRAY['unreviewed'::text, 'confirmed'::text, 'corrected'::text, 'rejected'::text])));
alter table public.memories add constraint memories_sensitivity_check CHECK ((sensitivity = ANY (ARRAY['normal'::text, 'sensitive'::text, 'high'::text])));
alter table public.memories add constraint memories_status_check CHECK ((status = ANY (ARRAY['do_not_store'::text, 'candidate'::text, 'confirmed'::text, 'update'::text, 'contradiction'::text, 'obsolete'::text])));
alter table public.memories add constraint memories_pkey PRIMARY KEY (id);
alter table public.hypotheses add constraint hypotheses_confidence_check CHECK (((confidence IS NULL) OR ((confidence >= (0)::numeric) AND (confidence <= (1)::numeric))));
alter table public.hypotheses add constraint hypotheses_status_check CHECK ((status = ANY (ARRAY['candidate'::text, 'validated'::text, 'modified'::text, 'discarded'::text])));
alter table public.hypotheses add constraint hypotheses_pkey PRIMARY KEY (id);
alter table public.situations add constraint situations_status_check CHECK ((status = ANY (ARRAY['open'::text, 'resolved'::text, 'paused'::text, 'obsolete'::text])));
alter table public.situations add constraint situations_pkey PRIMARY KEY (id);
alter table public.commitments add constraint commitments_perceived_difficulty_check CHECK (((perceived_difficulty IS NULL) OR ((perceived_difficulty >= 1) AND (perceived_difficulty <= 5))));
alter table public.commitments add constraint commitments_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'done'::text, 'not_done'::text, 'postponed'::text, 'obsolete'::text])));
alter table public.commitments add constraint commitments_pkey PRIMARY KEY (id);
alter table public.onboarding_sessions add constraint onboarding_sessions_status_check CHECK ((status = ANY (ARRAY['in_progress'::text, 'review'::text, 'completed'::text, 'skipped'::text])));
alter table public.onboarding_sessions add constraint onboarding_sessions_pkey PRIMARY KEY (id);
alter table public.profile_items add constraint profile_items_confidence_check CHECK (((confidence >= (0)::numeric) AND (confidence <= (1)::numeric)));
alter table public.profile_items add constraint profile_items_user_validation_check CHECK ((user_validation = ANY (ARRAY['unreviewed'::text, 'confirmed'::text, 'corrected'::text, 'rejected'::text])));
alter table public.profile_items add constraint profile_items_pkey PRIMARY KEY (id);
alter table public.brain_versions add constraint brain_versions_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'active'::text, 'retired'::text])));
alter table public.brain_versions add constraint brain_versions_pkey PRIMARY KEY (version);
alter table public.motivation_feedback add constraint motivation_feedback_rating_check CHECK ((rating = ANY (ARRAY['-1'::integer, 1])));
alter table public.motivation_feedback add constraint motivation_feedback_pkey PRIMARY KEY (id);
alter table public.agenda_events add constraint agenda_events_life_area_check CHECK ((life_area = ANY (ARRAY['relationship'::text, 'work'::text, 'family'::text, 'friends'::text, 'health'::text, 'self'::text, 'finance'::text, 'other'::text])));
alter table public.agenda_events add constraint agenda_events_event_kind_check CHECK ((event_kind = ANY (ARRAY['routine'::text, 'obligation'::text, 'goal'::text, 'decision'::text, 'challenge'::text, 'leisure'::text, 'commitment'::text])));
alter table public.agenda_events add constraint agenda_events_perceived_difficulty_check CHECK (((perceived_difficulty >= 1) AND (perceived_difficulty <= 5)));
alter table public.agenda_events add constraint agenda_events_source_check CHECK ((source = ANY (ARRAY['user'::text, 'selfia'::text, 'goal'::text, 'commitment'::text])));
alter table public.agenda_events add constraint agenda_events_pkey PRIMARY KEY (id);
alter table public.goals add constraint goals_life_area_check CHECK ((life_area = ANY (ARRAY['relationship'::text, 'work'::text, 'family'::text, 'friends'::text, 'health'::text, 'self'::text, 'finance'::text, 'other'::text])));
alter table public.goals add constraint goals_status_check CHECK ((status = ANY (ARRAY['active'::text, 'paused'::text, 'completed'::text, 'abandoned'::text])));
alter table public.goals add constraint goals_progress_state_check CHECK ((progress_state = ANY (ARRAY['starting'::text, 'progressing'::text, 'stable'::text, 'needs_attention'::text, 'blocked'::text, 'changing'::text, 'pending_decision'::text, 'improving'::text])));
alter table public.goals add constraint goals_pkey PRIMARY KEY (id);
alter table public.agenda_events add constraint agenda_events_status_check CHECK ((status = ANY (ARRAY['planned'::text, 'done'::text, 'partially_done'::text, 'not_done'::text, 'moved'::text, 'no_longer_relevant'::text, 'skipped_review'::text, 'cancelled'::text])));
alter table public.onboarding_sessions add constraint onboarding_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.onboarding_sessions add constraint onboarding_sessions_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE SET NULL;
alter table public.profiles add constraint profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.people add constraint people_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.conversations add constraint conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.messages add constraint messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.messages add constraint messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE;
alter table public.memories add constraint memories_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.memories add constraint memories_source_message_id_fkey FOREIGN KEY (source_message_id) REFERENCES messages(id) ON DELETE SET NULL;
alter table public.hypotheses add constraint hypotheses_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.situations add constraint situations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.commitments add constraint commitments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.commitments add constraint commitments_situation_id_fkey FOREIGN KEY (situation_id) REFERENCES situations(id) ON DELETE SET NULL;
alter table public.profile_items add constraint profile_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.profile_items add constraint profile_items_source_message_id_fkey FOREIGN KEY (source_message_id) REFERENCES messages(id) ON DELETE SET NULL;
alter table public.motivation_feedback add constraint motivation_feedback_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.agenda_events add constraint agenda_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.goals add constraint goals_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.agenda_events enable row level security;grant select,insert,update,delete on public.agenda_events to authenticated;
alter table public.brain_versions enable row level security;grant select,insert,update,delete on public.brain_versions to authenticated;
alter table public.commitments enable row level security;grant select,insert,update,delete on public.commitments to authenticated;
alter table public.conversations enable row level security;grant select,insert,update,delete on public.conversations to authenticated;
alter table public.goals enable row level security;grant select,insert,update,delete on public.goals to authenticated;
alter table public.hypotheses enable row level security;grant select,insert,update,delete on public.hypotheses to authenticated;
alter table public.memories enable row level security;grant select,insert,update,delete on public.memories to authenticated;
alter table public.messages enable row level security;grant select,insert,update,delete on public.messages to authenticated;
alter table public.motivation_feedback enable row level security;grant select,insert,update,delete on public.motivation_feedback to authenticated;
alter table public.onboarding_sessions enable row level security;grant select,insert,update,delete on public.onboarding_sessions to authenticated;
alter table public.people enable row level security;grant select,insert,update,delete on public.people to authenticated;
alter table public.profile_items enable row level security;grant select,insert,update,delete on public.profile_items to authenticated;
alter table public.profiles enable row level security;grant select,insert,update,delete on public.profiles to authenticated;
alter table public.situations enable row level security;grant select,insert,update,delete on public.situations to authenticated;
create policy own_profiles_select on public.profiles for SELECT to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) ;
create policy own_profiles_insert on public.profiles for INSERT to authenticated  with check ((( SELECT auth.uid() AS uid) = user_id));
create policy own_profiles_update on public.profiles for UPDATE to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) with check ((( SELECT auth.uid() AS uid) = user_id));
create policy own_profiles_delete on public.profiles for DELETE to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) ;
create policy agenda_events_select_own on public.agenda_events for SELECT to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) ;
create policy own_people_all on public.people for ALL to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) with check ((( SELECT auth.uid() AS uid) = user_id));
create policy own_conversations_all on public.conversations for ALL to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) with check ((( SELECT auth.uid() AS uid) = user_id));
create policy own_messages_all on public.messages for ALL to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) with check ((( SELECT auth.uid() AS uid) = user_id));
create policy own_memories_all on public.memories for ALL to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) with check ((( SELECT auth.uid() AS uid) = user_id));
create policy own_hypotheses_all on public.hypotheses for ALL to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) with check ((( SELECT auth.uid() AS uid) = user_id));
create policy own_situations_all on public.situations for ALL to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) with check ((( SELECT auth.uid() AS uid) = user_id));
create policy own_commitments_all on public.commitments for ALL to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) with check ((( SELECT auth.uid() AS uid) = user_id));
create policy own_onboarding_all on public.onboarding_sessions for ALL to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) with check ((( SELECT auth.uid() AS uid) = user_id));
create policy own_profile_items_all on public.profile_items for ALL to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) with check ((( SELECT auth.uid() AS uid) = user_id));
create policy deny_brain_versions_client on public.brain_versions for SELECT to authenticated using (false) ;
create policy motivation_feedback_select_own on public.motivation_feedback for SELECT to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) ;
create policy motivation_feedback_insert_own on public.motivation_feedback for INSERT to authenticated  with check ((( SELECT auth.uid() AS uid) = user_id));
create policy motivation_feedback_update_own on public.motivation_feedback for UPDATE to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) with check ((( SELECT auth.uid() AS uid) = user_id));
create policy agenda_events_insert_own on public.agenda_events for INSERT to authenticated  with check ((( SELECT auth.uid() AS uid) = user_id));
create policy agenda_events_update_own on public.agenda_events for UPDATE to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) with check ((( SELECT auth.uid() AS uid) = user_id));
create policy agenda_events_delete_own on public.agenda_events for DELETE to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) ;
create policy goals_select_own on public.goals for SELECT to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) ;
create policy goals_insert_own on public.goals for INSERT to authenticated  with check ((( SELECT auth.uid() AS uid) = user_id));
create policy goals_update_own on public.goals for UPDATE to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) with check ((( SELECT auth.uid() AS uid) = user_id));
create policy goals_delete_own on public.goals for DELETE to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) ;
